// SPDX-FileCopyrightText: Copyright (c) 2026 ChipFlow Inc. All rights reserved.
// SPDX-License-Identifier: Apache-2.0

//! GF180MCU standard-cell library support.
//!
//! Sibling of [`crate::sky130`]; together with [`crate::gf180mcu_pdk`] this
//! module provides cell detection, pin direction, and library identification
//! for GlobalFoundries' open-source 180 nm MCU PDK across both
//! `gf180mcu_fd_sc_mcu7t5v0` (7-track, 5 V) and `gf180mcu_fd_sc_mcu9t5v0`
//! (9-track, 5 V) standard-cell libraries.
//!
//! Cell-name convention:
//! `gf180mcu_fd_sc_<track>__<celltype>_<drive>`
//! e.g. `gf180mcu_fd_sc_mcu7t5v0__nand2_1`.
//!
//! IO pads (`gf180mcu_fd_io__*`), primitives (`gf180mcu_fd_pr__*`), and IP
//! blocks (`gf180mcu_fd_ip_*__*`) all share the `gf180mcu_fd_` prefix and
//! are detected as GF180MCU here so the netlist parser doesn't reject them.
//!
//! wafer.space variants — `gf180mcu_ws_io__*` (power pads) and
//! `gf180mcu_ws_ip__*` (id / logo stub modules) — share the `gf180mcu_ws_`
//! prefix and are recognised alongside the foundry-default `gf180mcu_fd_`
//! family. Post-P&R chip-tops built from the wafer.space project
//! template instantiate both, so detection accepts either.
//!
//! `extract_cell_type` strips the standard-cell, IO-pad, and IP prefixes
//! to a bare base-cell name. The classifiers in [`crate::gf180mcu_pdk`]
//! match on this bare name. Decomposition for the logic-bearing pads
//! (`in_c`, `in_s`, `bi_24t`) lives in [`crate::aig`]; pure no-logic
//! pads (fillers, power, corner, analog pass-through) are classified
//! as filler and skipped.

use compact_str::CompactString;
use netlistdb::{Direction, LeafPinProvider};
use sverilogparse::SVerilogRange;

// Generated by build.rs from the vendored cell-model submodules.
// Provides `GF180MCU_PIN_TABLE: &[(&str, &[(&str, Direction)])]`.
include!(concat!(env!("OUT_DIR"), "/gf180mcu_pins.rs"));

/// Foundry-default GF180MCU family (standard cells, fd_io pads, fd_pr
/// primitives, fd_ip_* IP).
const GF180MCU_FD_PREFIX: &str = "gf180mcu_fd_";

/// wafer.space variants of the GF180MCU library (ws_io power pads,
/// ws_ip id/logo stubs).
const GF180MCU_WS_PREFIX: &str = "gf180mcu_ws_";

const SC_7T_PREFIX: &str = "gf180mcu_fd_sc_mcu7t5v0__";
const SC_9T_PREFIX: &str = "gf180mcu_fd_sc_mcu9t5v0__";

/// Prefixes for non-standard-cell families whose macro name *is* the
/// base cell type (no drive-strength suffix). Strip these in
/// [`extract_cell_type`] so [`crate::gf180mcu_pdk`]'s classifiers can
/// match on bare names (`bi_24t`, `fill10`, `dvdd`, `id`, …).
const NON_SC_PREFIXES: &[&str] = &[
    "gf180mcu_fd_io__",
    "gf180mcu_fd_pr__",
    "gf180mcu_fd_ip_sram__",
    "gf180mcu_ws_io__",
    "gf180mcu_ws_ip__",
];

/// Is `name` any GF180MCU cell — standard cell, IO pad, primitive, IP,
/// or wafer.space variant (`gf180mcu_ws_*`)?
pub fn is_gf180mcu_cell(name: &str) -> bool {
    name.starts_with(GF180MCU_FD_PREFIX) || name.starts_with(GF180MCU_WS_PREFIX)
}

/// Strip the GF180MCU library prefix and the trailing drive-strength
/// suffix to recover the base cell type.
///
/// `gf180mcu_fd_sc_mcu7t5v0__nand2_1` → `nand2`.
/// `gf180mcu_fd_sc_mcu9t5v0__inv_20`  → `inv`.
/// `gf180mcu_fd_io__bi_24t`           → `bi_24t`  (no drive suffix on pads).
/// `gf180mcu_ws_io__dvdd`             → `dvdd`.
/// `gf180mcu_ws_ip__id`               → `id`.
///
/// Standard-cell drive suffixes are recognised as a trailing all-digit
/// component after the final underscore. Pad / IP macro names don't carry
/// a drive suffix, so the digit check leaves them intact (e.g. `asig_5p0`
/// → `asig_5p0`, since `5p0` contains a letter; `bi_24t` → `bi_24t`,
/// since `24t` contains a letter).
pub fn extract_cell_type(name: &str) -> &str {
    let stripped = name
        .strip_prefix(SC_7T_PREFIX)
        .or_else(|| name.strip_prefix(SC_9T_PREFIX))
        .or_else(|| NON_SC_PREFIXES.iter().find_map(|p| name.strip_prefix(p)))
        .unwrap_or(name);

    // Drive strength is always a numeric tail after the final underscore
    // — matches the SKY130 convention. Pad / IP macro names don't carry
    // a drive suffix; their base name is returned verbatim.
    if let Some(last_underscore) = stripped.rfind('_') {
        let suffix = &stripped[last_underscore + 1..];
        if !suffix.is_empty() && suffix.chars().all(|c| c.is_ascii_digit()) {
            return &stripped[..last_underscore];
        }
    }

    stripped
}

/// Hand-curated pin table for GF180MCU IO pads and wafer.space IP
/// stubs. Source: `gf180mcu/gf180mcuD/libs.ref/gf180mcu_fd_io/verilog/`
/// in the wafer.space PDK fork.
///
/// **Direction conventions inside the cell** (matches what NetlistDB
/// expects from `LeafPinProvider`):
///
/// * `bi_24t` (bidirectional pad): the digital-sim simplification
///   treats `PAD` as the external value (an input from the cell's POV).
///   `A` and `OE` are declared as inputs into the cell but their value
///   is discarded by `aig.rs::gf180mcu_postprocess` — they would only
///   matter if we modelled tristate, which Jacquard does not.
/// * `in_c` / `in_s`: `PAD` is the external input, `Y` is the internal
///   output. `PU` / `PD` exist but are sim-irrelevant inputs.
/// * `asig_5p0`: analog passthrough — has a single `ASIG5V` net that
///   Jacquard cannot model. Listed here only so NetlistDB can parse
///   the netlist; the cell is classified as filler downstream.
///
/// Power / corner / filler pads instantiate with `()` (no port
/// connections) in post-P&R netlists, so they never reach
/// `LeafPinProvider::direction_of`. They are still classified as
/// filler in [`crate::gf180mcu_pdk::is_filler_cell`].
const GF180MCU_PAD_PIN_TABLE: &[(&str, &[(&str, Direction)])] = &[
    ("in_c", &[
        ("PAD", Direction::I),
        ("PU", Direction::I),
        ("PD", Direction::I),
        ("Y", Direction::O),
    ]),
    ("in_s", &[
        ("PAD", Direction::I),
        ("PU", Direction::I),
        ("PD", Direction::I),
        ("Y", Direction::O),
    ]),
    ("bi_24t", &[
        // PAD is inout in Verilog. For digital sim with no tristate, we
        // treat it as an *input* to the cell — its value comes from the
        // top-level inout port, which Jacquard exposes as a primary
        // input.
        ("PAD", Direction::I),
        // The cell's `A` net comes from the core. In digital sim with
        // no tristate we discard it (the cell does not drive Y from A).
        ("A", Direction::I),
        ("OE", Direction::I),
        ("IE", Direction::I),
        ("CS", Direction::I),
        ("SL", Direction::I),
        ("PU", Direction::I),
        ("PD", Direction::I),
        ("Y", Direction::O),
    ]),
    ("asig_5p0", &[
        // Analog passthrough — has one port. Classified as filler,
        // contributes no logic.
        ("ASIG5V", Direction::I),
    ]),
];

/// LeafPinProvider for the full GF180MCU library — standard cells,
/// IO pads, and wafer.space IP stubs.
///
/// All cell pins are scalar (no bus pins), so `width_of` returns `None`.
/// Standard-cell directions come from the build.rs-generated
/// `GF180MCU_PIN_TABLE`; pad / IP directions come from the hand-curated
/// `GF180MCU_PAD_PIN_TABLE` above.
pub struct GF180MCULeafPins;

impl LeafPinProvider for GF180MCULeafPins {
    fn direction_of(
        &self,
        macro_name: &CompactString,
        pin_name: &CompactString,
        _pin_idx: Option<isize>,
    ) -> Direction {
        // Power / ground pins follow a fixed naming convention across both
        // the standard-cell and pad libraries and are always Inout. Short-
        // circuiting here sidesteps per-cell table drift: the vendored
        // Verilog cell models declare power pins as `inout` (e.g.
        // `inout VDD, VSS;` on antenna) but build.rs only parses
        // `input`/`output` declarations, so the generated GF180MCU_PIN_TABLE
        // is missing them. The post-PnR netlist connects them explicitly,
        // which otherwise panics on the first VDD lookup. The name set
        // lives in `gf180mcu_pdk::POWER_PIN_NAMES` so the clock-tracing
        // pin-enumeration skip in aig.rs uses the same source of truth.
        if crate::gf180mcu_pdk::is_power_pin(pin_name.as_str()) {
            // Direction enum in eda-infra-rs has no `Inout` variant
            // (I / O / Unknown only). Power pins are effectively inputs —
            // driven from the supply, never driven by the cell — so `I`
            // matches the simulator's "constant external driver" semantics.
            // DVDD/DVSS/AVDD/AVSS are wafer.space-PDK power-pad naming.
            return Direction::I;
        }
        let cell_type = extract_cell_type(macro_name);
        // Filler / endcap / fill1-10 / corner pads: upstream assumes these
        // instantiate with `()` (no port connections) in post-P&R netlists,
        // but the wafer.space `gf180mcu-project-template` wires
        // VDD/VSS/DVDD/DVSS/etc. on every filler instance. Treat any wired
        // pin on a known filler as a constant input — no logic effect.
        if crate::gf180mcu_pdk::is_filler_cell(cell_type) {
            return Direction::I;
        }
        // Standard cells first (the hot path).
        for (ct, pins) in GF180MCU_PIN_TABLE {
            if *ct == cell_type {
                for (p, d) in *pins {
                    if *p == pin_name.as_str() {
                        return *d;
                    }
                }
                panic!(
                    "Unknown gf180mcu pin on cell type '{cell_type}': \
                     macro={macro_name}, pin={pin_name}",
                );
            }
        }
        // Then pads / IP stubs.
        for (ct, pins) in GF180MCU_PAD_PIN_TABLE {
            if *ct == cell_type {
                for (p, d) in *pins {
                    if *p == pin_name.as_str() {
                        return *d;
                    }
                }
                panic!(
                    "Unknown gf180mcu pad pin on cell type '{cell_type}': \
                     macro={macro_name}, pin={pin_name}",
                );
            }
        }
        panic!(
            "Unknown gf180mcu cell (no pin-table entry for type '{cell_type}'): \
             macro={macro_name}",
        );
    }

    fn width_of(
        &self,
        _macro_name: &CompactString,
        _pin_name: &CompactString,
    ) -> Option<SVerilogRange> {
        None
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn detects_standard_cells_in_both_variants() {
        assert!(is_gf180mcu_cell("gf180mcu_fd_sc_mcu7t5v0__nand2_1"));
        assert!(is_gf180mcu_cell("gf180mcu_fd_sc_mcu9t5v0__nand2_1"));
    }

    #[test]
    fn detects_io_pr_and_ip_families() {
        assert!(is_gf180mcu_cell("gf180mcu_fd_io__bi_24t"));
        assert!(is_gf180mcu_cell("gf180mcu_fd_pr__nmos_3p3"));
        assert!(is_gf180mcu_cell("gf180mcu_fd_ip_sram__sram64x16m8wm1"));
    }

    #[test]
    fn detects_wafer_space_variants() {
        // Post-P&R chip-tops from the wafer.space project template
        // instantiate `gf180mcu_ws_io__*` power pads and
        // `gf180mcu_ws_ip__*` IP stubs alongside foundry-default
        // `gf180mcu_fd_*` cells. Both prefixes must be detected.
        assert!(is_gf180mcu_cell("gf180mcu_ws_io__dvdd"));
        assert!(is_gf180mcu_cell("gf180mcu_ws_io__dvss"));
        assert!(is_gf180mcu_cell("gf180mcu_ws_ip__id"));
        assert!(is_gf180mcu_cell("gf180mcu_ws_ip__logo"));
    }

    #[test]
    fn rejects_non_gf180mcu_names() {
        assert!(!is_gf180mcu_cell("sky130_fd_sc_hd__nand2_1"));
        assert!(!is_gf180mcu_cell("AND2_00_0"));
        assert!(!is_gf180mcu_cell(""));
        assert!(!is_gf180mcu_cell("gf180mcu"));
        // Plausible-looking but wrong family prefix.
        assert!(!is_gf180mcu_cell("gf180mcu_xx_io__foo"));
    }

    #[test]
    fn extracts_base_cell_type_across_variants() {
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__inv_1"), "inv");
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__inv_20"), "inv");
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu9t5v0__nand2_4"), "nand2");
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu9t5v0__dffq_1"), "dffq");
        assert_eq!(
            extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__aoi222_1"),
            "aoi222"
        );
    }

    #[test]
    fn extraction_handles_dff_with_polarity_in_name() {
        // The 'n' in dffnq / dffnrnq is part of the cell type, not a
        // drive-strength suffix — the drive number is the trailing _1.
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__dffnq_1"), "dffnq");
        assert_eq!(extract_cell_type("gf180mcu_fd_sc_mcu7t5v0__dffnrsnq_2"), "dffnrsnq");
    }

    #[test]
    fn extraction_passes_through_unprefixed_names() {
        // Unprefixed names still get numeric-suffix stripping.
        assert_eq!(extract_cell_type("inv_1"), "inv");
        // Non-numeric tails are left intact — no false trim.
        assert_eq!(extract_cell_type("not_a_cell"), "not_a_cell");
        assert_eq!(extract_cell_type("plain"), "plain");
    }

    #[test]
    fn extraction_strips_non_standard_cell_prefixes() {
        // IO pads (no drive suffix on pad cells).
        assert_eq!(extract_cell_type("gf180mcu_fd_io__bi_24t"), "bi_24t");
        assert_eq!(extract_cell_type("gf180mcu_fd_io__in_c"), "in_c");
        assert_eq!(extract_cell_type("gf180mcu_fd_io__in_s"), "in_s");
        assert_eq!(extract_cell_type("gf180mcu_fd_io__fill10"), "fill10");
        assert_eq!(extract_cell_type("gf180mcu_fd_io__fill5"), "fill5");
        assert_eq!(extract_cell_type("gf180mcu_fd_io__fill1"), "fill1");
        assert_eq!(extract_cell_type("gf180mcu_fd_io__fillnc"), "fillnc");
        assert_eq!(extract_cell_type("gf180mcu_fd_io__cor"), "cor");
        // asig_5p0 has a literal _5p0 tail that must NOT be stripped
        // (it's part of the cell name, not a drive suffix).
        assert_eq!(extract_cell_type("gf180mcu_fd_io__asig_5p0"), "asig_5p0");
        // wafer.space pads / IP.
        assert_eq!(extract_cell_type("gf180mcu_ws_io__dvdd"), "dvdd");
        assert_eq!(extract_cell_type("gf180mcu_ws_io__dvss"), "dvss");
        assert_eq!(extract_cell_type("gf180mcu_ws_ip__id"), "id");
        assert_eq!(extract_cell_type("gf180mcu_ws_ip__logo"), "logo");
        // SRAM IP.
        assert_eq!(
            extract_cell_type("gf180mcu_fd_ip_sram__sram64x16m8wm1"),
            "sram64x16m8wm1",
        );
    }

    #[test]
    fn pin_table_covers_full_cell_catalogue() {
        // 7t and 9t share an identical 69-cell catalogue per the gf180mcu
        // README; the generated table is deduped by base cell type, so we
        // expect exactly 69 entries.
        assert_eq!(GF180MCU_PIN_TABLE.len(), 69, "expected 69 cell types");
    }

    #[test]
    fn pin_provider_returns_expected_directions() {
        let provider = GF180MCULeafPins;
        let dir = |cell: &str, pin: &str| {
            provider.direction_of(
                &CompactString::from(cell),
                &CompactString::from(pin),
                None,
            )
        };
        // Spot-check across cell families.
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__inv_1", "I"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__inv_20", "ZN"), Direction::O);
        assert_eq!(dir("gf180mcu_fd_sc_mcu9t5v0__nand2_4", "A1"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_sc_mcu9t5v0__nand2_4", "ZN"), Direction::O);
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__dffq_1", "CLK"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__dffq_1", "D"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__dffq_1", "Q"), Direction::O);
        // notifier is in the cell's port list — must be modeled as an input
        // so synthesis output naming it doesn't reject as unknown.
        assert_eq!(dir("gf180mcu_fd_sc_mcu7t5v0__dffq_1", "notifier"), Direction::I);
    }

    #[test]
    fn pin_provider_handles_both_variants_identically() {
        let provider = GF180MCULeafPins;
        for cell in ["aoi22_1", "dffrnq_1", "mux2_1"] {
            let pin = "Q"; // not all of these have Q; only DFF does — we'll branch
            let _ = pin;
            let pin_in = match cell {
                "aoi22_1" => "A1",
                "dffrnq_1" => "CLK",
                "mux2_1" => "I0",
                _ => unreachable!(),
            };
            let macro_7t = CompactString::from(format!("gf180mcu_fd_sc_mcu7t5v0__{cell}"));
            let macro_9t = CompactString::from(format!("gf180mcu_fd_sc_mcu9t5v0__{cell}"));
            let pin_cs = CompactString::from(pin_in);
            assert_eq!(
                provider.direction_of(&macro_7t, &pin_cs, None),
                provider.direction_of(&macro_9t, &pin_cs, None),
                "7t/9t disagreed on {cell}.{pin_in}",
            );
        }
    }

    #[test]
    fn pin_provider_returns_directions_for_io_pads() {
        // Post-P&R chip-top netlists wire these three pad families
        // with port connections (PAD, Y, A, OE, etc.). The pin
        // provider must return directions for each, otherwise
        // NetlistDB parse panics.
        let provider = GF180MCULeafPins;
        let dir = |cell: &str, pin: &str| {
            provider.direction_of(
                &CompactString::from(cell),
                &CompactString::from(pin),
                None,
            )
        };

        // in_c (CMOS input pad): PAD in, Y out, plus sim-irrelevant
        // PU / PD pull controls.
        assert_eq!(dir("gf180mcu_fd_io__in_c", "PAD"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_io__in_c", "Y"), Direction::O);
        assert_eq!(dir("gf180mcu_fd_io__in_c", "PU"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_io__in_c", "PD"), Direction::I);

        // in_s (Schmitt input pad): same shape as in_c.
        assert_eq!(dir("gf180mcu_fd_io__in_s", "PAD"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_io__in_s", "Y"), Direction::O);

        // bi_24t (bidirectional pad): in digital sim, PAD is the
        // external input and Y is the internal output. A / OE / IE
        // are declared as cell inputs but discarded by the AIG
        // post-process (no tristate).
        assert_eq!(dir("gf180mcu_fd_io__bi_24t", "PAD"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_io__bi_24t", "Y"), Direction::O);
        assert_eq!(dir("gf180mcu_fd_io__bi_24t", "A"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_io__bi_24t", "OE"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_io__bi_24t", "IE"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_io__bi_24t", "CS"), Direction::I);
        assert_eq!(dir("gf180mcu_fd_io__bi_24t", "SL"), Direction::I);

        // asig_5p0 (analog passthrough — classified as filler, but
        // its ASIG5V port is wired in real chip-top netlists, so the
        // pin table needs an entry to satisfy NetlistDB parse).
        assert_eq!(dir("gf180mcu_fd_io__asig_5p0", "ASIG5V"), Direction::I);
    }

    #[test]
    fn pin_provider_width_is_always_scalar() {
        let provider = GF180MCULeafPins;
        // No bus pins in the standard-cell library.
        assert!(provider
            .width_of(
                &CompactString::from("gf180mcu_fd_sc_mcu7t5v0__nand2_1"),
                &CompactString::from("A1"),
            )
            .is_none());
    }

    #[test]
    fn aig_builds_from_combinational_gf180mcu_netlist() {
        // End-to-end: gf180mcu Verilog → NetlistDB → AIG. Exercises
        // the full Phase 4 path: GF180MCULeafPins, library detection,
        // load_pdk_models, decompose_combinational, AIG integration.
        const VERILOG: &str = r#"
module tiny(A, B, C, Y, Z);
  input A, B, C;
  output Y, Z;
  wire mid;
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 u1 (.A1(A), .A2(B), .ZN(mid));
  gf180mcu_fd_sc_mcu9t5v0__inv_1   u2 (.I(mid), .ZN(Y));
  gf180mcu_fd_sc_mcu7t5v0__or3_1   u3 (.A1(A), .A2(B), .A3(C), .Z(Z));
endmodule
"#;
        let nl = netlistdb::NetlistDB::from_sverilog_source(
            VERILOG,
            Some("tiny"),
            &GF180MCULeafPins,
        )
        .expect("netlist parse");
        let aig = crate::aig::AIG::from_netlistdb(&nl);
        // NAND2 + INV cancel out (NAND followed by INV = AND), and OR3
        // decomposes to a chain of AND gates with input/output inversion.
        // Exact AIG-pin count varies with synthesis choices; just assert
        // construction succeeded and produced a non-empty AIG.
        assert!(aig.num_aigpins > 0, "AIG should have at least one pin");
    }

    #[test]
    fn aig_clock_trace_skips_power_pins_on_clkbuf() {
        // Regression for #70: post-#64, power pins on a clkbuf resolve to
        // `Direction::I`, which made the clock-tracing pin-enumeration
        // loop treat them as unrecognised signal inputs and panic with
        // "input pin VDD unexpected for ck element ... multi-input cell
        // ... clock gating need to be manually patched."
        //
        // Synthetic shape: a single DFF clocked through a clkbuf that
        // has VDD / VSS wired (the real-world chip_top.pnl.v pattern).
        // Without the fix the AIG::from_netlistdb call panics during
        // clock tracing.
        const VERILOG: &str = r#"
module tiny(CLK_PAD, D, Q);
  input CLK_PAD, D;
  output Q;
  wire CLK_INTERNAL, VDD, VSS, notifier;
  // Clock buffer with realistic power-pin wiring.
  gf180mcu_fd_sc_mcu9t5v0__clkbuf_8 CLKBUF_1 (
      .I(CLK_PAD), .Z(CLK_INTERNAL), .VDD(VDD), .VSS(VSS), .VNW(VDD), .VPW(VSS)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 DFF_1 (
      .CLK(CLK_INTERNAL), .D(D), .Q(Q), .notifier(notifier)
  );
endmodule
"#;
        let nl = netlistdb::NetlistDB::from_sverilog_source(
            VERILOG,
            Some("tiny"),
            &GF180MCULeafPins,
        )
        .expect("netlist parse");
        // The actual test: this used to panic. After the fix, AIG
        // construction completes without error.
        let aig = crate::aig::AIG::from_netlistdb(&nl);
        assert!(
            aig.num_aigpins > 0,
            "AIG should have at least one pin after clock tracing"
        );
    }

    #[test]
    fn aig_clock_trace_accepts_delay_cells_on_clock_path() {
        // Regression for #73: OpenROAD's hold-fixing pass inserts
        // `dlyd_*` / `dlya_*` / `dlyb_*` / `dlyc_*` delay cells on
        // clock fanout to repair tight hold paths. These are
        // functionally identity buffers (I → Z, no negation, no
        // gating) so clock tracing should pass through them the
        // same way it passes through `clkbuf` / `buf` cells.
        // Before the fix the clock-tracer rejected the cell type
        // and panicked with "multi-input cell ⇒ clock gating".
        //
        // Synthetic shape: a DFF clocked through `clkbuf → dlyd → DFF`
        // (OpenROAD's typical hold-fix-on-clock-fanout pattern).
        const VERILOG: &str = r#"
module tiny(CLK_PAD, D, Q);
  input CLK_PAD, D;
  output Q;
  wire CLK_BUF, CLK_DLY, VDD, VSS, notifier;
  gf180mcu_fd_sc_mcu9t5v0__clkbuf_8 CLKBUF_1 (
      .I(CLK_PAD), .Z(CLK_BUF), .VDD(VDD), .VSS(VSS), .VNW(VDD), .VPW(VSS)
  );
  gf180mcu_fd_sc_mcu9t5v0__dlyd_1 DLY_1 (
      .I(CLK_BUF), .Z(CLK_DLY), .VDD(VDD), .VSS(VSS), .VNW(VDD), .VPW(VSS)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 DFF_1 (
      .CLK(CLK_DLY), .D(D), .Q(Q), .notifier(notifier)
  );
endmodule
"#;
        let nl = netlistdb::NetlistDB::from_sverilog_source(
            VERILOG,
            Some("tiny"),
            &GF180MCULeafPins,
        )
        .expect("netlist parse");
        // Used to panic in clock tracing on the dlyd_1 cell.
        let aig = crate::aig::AIG::from_netlistdb(&nl);
        assert!(
            aig.num_aigpins > 0,
            "AIG should have at least one pin after clock tracing through dlyd"
        );
    }

    #[test]
    fn aig_clock_trace_accepts_bi_24t_on_clock_path() {
        // Regression for #75: bidirectional IO pads on the clock
        // path. The wafer.space `gf180mcu-project-template` default
        // routes JTAG TCK (and any other debug clock) through the
        // standard `bi_24t` signal-pad slot rather than dedicating
        // an input-only pad to it. `bi_24t` is digitally simplified
        // to `Y = PAD` (see is_io_pad_cell in gf180mcu_pdk.rs), so
        // the clock-trace shape is identical to in_c / in_s — but
        // it has an extra wrinkle: `A` and `OE` are also
        // Direction::I (the core-side tristate driver inputs that
        // get discarded). The pin enumeration must pick `PAD` as
        // the clock source, not `A`.
        //
        // Synthetic shape: a DFF clocked through bi_24t (PAD →
        // Y → DFF.CLK), with A and OE wired to constants the way
        // a no-tristate output-disable wiring would look.
        const VERILOG: &str = r#"
module tiny(TCK_PAD, D, Q);
  inout TCK_PAD;
  input D;
  output Q;
  wire CLK_CORE, VDD, VSS, notifier;
  gf180mcu_fd_io__bi_24t TCK_PAD_INST (
      .PAD(TCK_PAD), .Y(CLK_CORE), .A(1'b0), .OE(1'b0),
      .IE(1'b1), .PU(1'b0), .PD(1'b0), .CS(1'b0), .SL(1'b0)
  );
  gf180mcu_fd_sc_mcu7t5v0__dffq_1 DFF_1 (
      .CLK(CLK_CORE), .D(D), .Q(Q), .notifier(notifier)
  );
endmodule
"#;
        let nl = netlistdb::NetlistDB::from_sverilog_source(
            VERILOG,
            Some("tiny"),
            &GF180MCULeafPins,
        )
        .expect("netlist parse");
        // Used to panic in clock tracing — bi_24t wasn't on the
        // is_io_pad_buf whitelist.
        let aig = crate::aig::AIG::from_netlistdb(&nl);
        assert!(
            aig.num_aigpins > 0,
            "AIG should have at least one pin after clock tracing through bi_24t"
        );
    }

    #[test]
    fn netlist_db_parses_chip_top_pad_ring() {
        // Miniature GF180MCU chip-top: full pad ring around a trivial
        // core, covering every pad family that real post-P&R netlists
        // instantiate. Verifies that:
        //   * `is_gf180mcu_cell` accepts both `gf180mcu_fd_*` and
        //     `gf180mcu_ws_*` prefixes, so NetlistDB doesn't reject;
        //   * `extract_cell_type` returns base names the pin table
        //     and filler classifier can match;
        //   * `GF180MCU_PAD_PIN_TABLE` covers every connected pad pin
        //     (in_c / in_s / bi_24t / asig_5p0).
        // AIG construction is out of scope for this test — it's
        // exercised end-to-end by an aig.rs-side integration test.
        const VERILOG: &str = r#"
module chip_top(clk_PAD, in_PAD, bidir_PAD, analog_PAD);
  inout clk_PAD;
  inout in_PAD;
  inout bidir_PAD;
  inout analog_PAD;
  wire clk_core, in_core, bidir_y_core, bidir_a_core, oe_core;
  // Logic-bearing pads.
  gf180mcu_fd_io__in_s clk_pad (.PAD(clk_PAD), .PU(1'b0), .PD(1'b0), .Y(clk_core));
  gf180mcu_fd_io__in_c in_pad  (.PAD(in_PAD),  .PU(1'b0), .PD(1'b0), .Y(in_core));
  gf180mcu_fd_io__bi_24t bidir_pad (
      .PAD(bidir_PAD), .A(bidir_a_core), .OE(oe_core),
      .IE(1'b1), .CS(1'b0), .SL(1'b0), .PU(1'b0), .PD(1'b0),
      .Y(bidir_y_core)
  );
  // Analog passthrough (classified as filler, but its ASIG5V port
  // is connected so the pin table must cover it).
  gf180mcu_fd_io__asig_5p0 asig_inst (.ASIG5V(analog_PAD));
  // No-logic pads — empty port lists. Matches post-P&R netlists,
  // where filler / corner / power / ws_ip stubs have no port
  // connections.
  gf180mcu_fd_io__fill10 fill_inst ();
  gf180mcu_fd_io__cor    cor_inst  ();
  gf180mcu_ws_io__dvdd   dvdd_inst ();
  gf180mcu_ws_io__dvss   dvss_inst ();
  gf180mcu_ws_ip__id     id_inst   ();
  gf180mcu_ws_ip__logo   logo_inst ();
endmodule
"#;
        let nl = netlistdb::NetlistDB::from_sverilog_source(
            VERILOG,
            Some("chip_top"),
            &GF180MCULeafPins,
        );
        assert!(
            nl.is_some(),
            "NetlistDB parse failed for chip_top pad ring — \
             pin table likely missing an entry",
        );
    }

    #[test]
    fn pin_provider_returns_directions_for_power_and_ground_pins() {
        // Antenna / endcap / decoupling cells declare `inout VDD, VSS;` in
        // their Verilog models; `build.rs` only parses `input` / `output`,
        // so VDD / VSS were missing from the generated pin table. Real
        // post-P&R netlists wire them — without the power-pin shortcut,
        // NetlistDB parse panics on the first wired `.VDD(...)`.
        let provider = GF180MCULeafPins;
        let dir = |cell: &str, pin: &str| {
            provider.direction_of(
                &CompactString::from(cell),
                &CompactString::from(pin),
                None,
            )
        };
        for pin in [
            "VDD", "VSS", "VNW", "VPW", "VPB", "VNB", "VPWR", "VGND",
            "DVDD", "DVSS", "AVDD", "AVSS",
        ] {
            // Shortcut is per-pin-name, not per-cell, so any cell works.
            assert_eq!(
                dir("gf180mcu_fd_sc_mcu7t5v0__antenna", pin),
                Direction::I,
                "{pin} should resolve to Direction::I on antenna"
            );
        }
    }

    #[test]
    fn pin_provider_handles_wired_filler_and_corner_cells() {
        // wafer.space `gf180mcu-project-template` post-P&R netlists wire
        // power pins on every filler / corner / power-pad instance, e.g.
        //   gf180mcu_fd_io__cor IO_CORNER_NE (.DVDD(VDD), .DVSS(VSS),
        //                                     .VDD(VDD),  .VSS(VSS));
        // Upstream assumed these always instantiate with `()` (no
        // connections), so the pin table has no entry for filler pins.
        // The filler-cell shortcut treats any pin on a known filler as
        // Direction::I — the cell has no logic, so power/ground/signal
        // are all "constant external driver" from the AIG's perspective.
        let provider = GF180MCULeafPins;
        let dir = |cell: &str, pin: &str| {
            provider.direction_of(
                &CompactString::from(cell),
                &CompactString::from(pin),
                None,
            )
        };
        // Corner pad (`cor`) — wired with DVDD / DVSS / VDD / VSS.
        for pin in ["DVDD", "DVSS", "VDD", "VSS"] {
            assert_eq!(dir("gf180mcu_fd_io__cor", pin), Direction::I);
        }
        // IO filler — wired with VDD / VSS.
        for pin in ["VDD", "VSS"] {
            assert_eq!(dir("gf180mcu_fd_io__fill10", pin), Direction::I);
        }
        // Standard-cell filler / endcap — wired with VDD / VSS.
        for pin in ["VDD", "VSS"] {
            assert_eq!(dir("gf180mcu_fd_sc_mcu9t5v0__filltie", pin), Direction::I);
            assert_eq!(dir("gf180mcu_fd_sc_mcu9t5v0__endcap", pin), Direction::I);
        }
        // wafer.space power pads — DVDD / DVSS instances themselves.
        for pin in ["DVDD", "DVSS", "VDD", "VSS"] {
            assert_eq!(dir("gf180mcu_ws_io__dvdd", pin), Direction::I);
            assert_eq!(dir("gf180mcu_ws_io__dvss", pin), Direction::I);
        }
    }

    #[test]
    fn netlist_db_parses_wired_chip_top_pad_ring() {
        // Same shape as the `_parses_chip_top_pad_ring` test above, but
        // with realistic wired-up power/ground connections matching what
        // OpenROAD emits in post-P&R netlists (`gf180mcu-project-template`
        // LibreLane flow). Catches regressions where the pin table or
        // shortcuts drift from real netlists.
        const VERILOG: &str = r#"
module chip_top(clk_PAD);
  inout clk_PAD;
  wire clk_core, mid, VDD, VSS;
  // Logic-bearing pad — already covered by the pad pin table.
  gf180mcu_fd_io__in_s clk_pad (.PAD(clk_PAD), .PU(1'b0), .PD(1'b0), .Y(clk_core));
  // Antenna cell with wired `inout VDD, VNW, VPW, VSS`.
  gf180mcu_fd_sc_mcu7t5v0__antenna ANTENNA_1 (
      .I(clk_core), .VDD(VDD), .VNW(VDD), .VPW(VSS), .VSS(VSS)
  );
  // Inverter so the design is non-degenerate.
  gf180mcu_fd_sc_mcu9t5v0__inv_1 U1 (.I(clk_core), .ZN(mid));
  // Corner pad — wired DVDD / DVSS / VDD / VSS, no signal pins.
  gf180mcu_fd_io__cor IO_CORNER_NE_INST (
      .DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS)
  );
  // IO filler — wired VDD / VSS.
  gf180mcu_fd_io__fill10 IO_FILL_1 (.VDD(VDD), .VSS(VSS));
  // Standard-cell filltie / endcap — wired VDD / VSS.
  gf180mcu_fd_sc_mcu9t5v0__filltie FILLTIE_1 (.VDD(VDD), .VSS(VSS));
  gf180mcu_fd_sc_mcu9t5v0__endcap  ENDCAP_1  (.VDD(VDD), .VSS(VSS));
  // wafer.space power pads.
  gf180mcu_ws_io__dvdd DVDD_INST (.DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS));
  gf180mcu_ws_io__dvss DVSS_INST (.DVDD(VDD), .DVSS(VSS), .VDD(VDD), .VSS(VSS));
endmodule
"#;
        let nl = netlistdb::NetlistDB::from_sverilog_source(
            VERILOG,
            Some("chip_top"),
            &GF180MCULeafPins,
        );
        assert!(
            nl.is_some(),
            "NetlistDB parse failed for wired chip_top pad ring — \
             power-pin or filler-cell shortcut missing",
        );
    }

    #[test]
    fn netlist_db_round_trips_a_mixed_7t_9t_design() {
        // Exercise the full LeafPinProvider contract through NetlistDB —
        // catches missing pin entries, mis-typed directions, and any
        // bus-width assumption the parser makes.
        const VERILOG: &str = r#"
module tiny(A, B, CLK, Y, Q);
  input A, B, CLK;
  output Y, Q;
  wire mid, q1, notifier;
  gf180mcu_fd_sc_mcu7t5v0__nand2_1 u1 (.A1(A), .A2(B), .ZN(mid));
  gf180mcu_fd_sc_mcu9t5v0__inv_1   u2 (.I(mid), .ZN(Y));
  gf180mcu_fd_sc_mcu7t5v0__dffq_1  u3 (.CLK(CLK), .D(mid), .Q(q1), .notifier(notifier));
  gf180mcu_fd_sc_mcu9t5v0__inv_1   u4 (.I(q1), .ZN(Q));
endmodule
"#;
        let nl = netlistdb::NetlistDB::from_sverilog_source(VERILOG, Some("tiny"), &GF180MCULeafPins);
        assert!(nl.is_some(), "NetlistDB construction failed");
    }
}
