// SPDX-FileCopyrightText: Copyright (c) 2024 NVIDIA CORPORATION & AFFILIATES. All rights reserved.
// SPDX-License-Identifier: Apache-2.0
//! SKY130 standard cell library support for GEM.
//!
//! This module provides pin direction and width information for the SKY130
//! open-source PDK standard cells. SKY130 cells follow the naming convention:
//! `sky130_fd_sc_<variant>__<celltype>_<drive>`
//!
//! Supported variants: hd (high-density), hs (high-speed), ms (medium-speed)

use compact_str::CompactString;
use netlistdb::{Direction, LeafPinProvider};
use sverilogparse::SVerilogRange;

// Generated by build.rs from vendor/sky130_fd_sc_hd/cells. Provides
// `SKY130_PIN_TABLE: &[(&str, &[(&str, Direction)])]` — the
// authoritative pin-direction table for every SKY130 standard cell
// (drive-strength suffix already stripped). Consumed below by
// `SKY130LeafPins::direction_of` via exact lookup, mirroring the
// gf180mcu pattern. The previous hand-rolled prefix-match arms were
// missing entries for ~42 cell families (DFFs with `Q_N`, neg-edge
// DFFs, set+reset DFFs, scan / DE / latch variants, tristate buffers,
// `fa` variants with named SUM/COUT, low-power isolation, probe /
// spare cells) — all of which the build.rs-generated table covers
// correctly. The shadow bug where `t.starts_with("buf")` swallowed
// `bufinv_*` (panic on `Y`) likewise disappears with exact lookup.
mod generated {
    use netlistdb::Direction;
    include!(concat!(env!("OUT_DIR"), "/sky130_pins.rs"));
}

use generated::SKY130_PIN_TABLE;

/// LeafPinProvider implementation for SKY130 standard cells.
///
/// Standard-cell pin directions come from the build.rs-generated
/// `SKY130_PIN_TABLE`. The ChipFlow `CF_SRAM_*` macros and the bare
/// AIGPDK `INV` cell (which sometimes appears inline in SKY130
/// netlists synthesized from `assign ~expr`) are handled out of band
/// because they are not part of the vendored cell catalogue.
pub struct SKY130LeafPins;

impl LeafPinProvider for SKY130LeafPins {
    fn direction_of(
        &self,
        macro_name: &CompactString,
        pin_name: &CompactString,
        _pin_idx: Option<isize>,
    ) -> Direction {
        let cell_type = extract_cell_type(macro_name);
        let pin = pin_name.as_str();

        // AIGPDK INV (synthesized from `assign ~expr`); not in the
        // SKY130 cell catalogue but can appear inline in mixed
        // netlists. `extract_cell_type("INV")` returns "INV" verbatim
        // because there is no library prefix to strip.
        if cell_type == "INV" {
            return match pin {
                "A" => Direction::I,
                "Y" => Direction::O,
                _ => unknown_pin(macro_name, pin_name),
            };
        }

        // Standard cells: exact lookup against the generated table.
        for (ct, pins) in SKY130_PIN_TABLE {
            if *ct == cell_type {
                for (p, d) in *pins {
                    if *p == pin {
                        return *d;
                    }
                }
                panic!(
                    "Unknown SKY130 pin on cell type '{cell_type}': \
                     macro={macro_name}, pin={pin_name}",
                );
            }
        }

        // ChipFlow SRAM macros (`CF_SRAM_*`) — not in the SKY130 cell
        // catalogue. Match on the full macro name (no prefix-stripping
        // applies here).
        if macro_name.starts_with("CF_SRAM_") {
            return match pin {
                // Control inputs
                "WLBI" | "WLOFF" | "CLKin" | "EN" | "R_WB" | "SM" | "TM" => Direction::I,
                "ScanInDR" | "ScanInDL" | "ScanInCC" => Direction::I,
                "vpwrpc" | "vpwrac" => Direction::I,
                // Data/address inputs
                "AD" | "BEN" | "DI" => Direction::I,
                // Data/scan outputs
                "DO" | "ScanOutCC" => Direction::O,
                _ => unknown_pin(macro_name, pin_name),
            };
        }

        panic!(
            "Unknown SKY130 cell (no pin-table entry for type '{cell_type}'): \
             macro={macro_name}",
        );
    }

    fn width_of(
        &self,
        macro_name: &CompactString,
        pin_name: &CompactString,
    ) -> Option<SVerilogRange> {
        // Check for ChipFlow SRAM macros which have bus pins
        if macro_name.starts_with("CF_SRAM_") {
            match pin_name.as_str() {
                // Data buses are 32-bit
                "DO" | "DI" | "BEN" => Some(SVerilogRange(31, 0)),
                // Address bus - width depends on SRAM depth
                // CF_SRAM_1024x32 has 10-bit address (2^10 = 1024)
                "AD" => Some(SVerilogRange(9, 0)),
                // All other pins are single-bit
                _ => None,
            }
        } else {
            // All SKY130 standard cells have single-bit pins
            None
        }
    }
}

/// Extract the cell type from a SKY130 macro name.
///
/// Converts `sky130_fd_sc_hd__inv_2` to `inv`.
pub fn extract_cell_type(name: &str) -> &str {
    // First strip the library prefix
    let stripped = name
        .strip_prefix("sky130_fd_sc_hd__")
        .or_else(|| name.strip_prefix("sky130_fd_sc_hs__"))
        .or_else(|| name.strip_prefix("sky130_fd_sc_ms__"))
        .or_else(|| name.strip_prefix("sky130_fd_sc_ls__"))
        .or_else(|| name.strip_prefix("sky130_fd_sc_lp__"))
        .or_else(|| name.strip_prefix("sky130_fd_sc_hdll__"))
        .or_else(|| name.strip_prefix("sky130_fd_sc_hvl__"))
        .unwrap_or(name);

    // Then strip the drive strength suffix (e.g., _2, _4, _16)
    // The drive strength is always a number at the end after an underscore
    if let Some(last_underscore) = stripped.rfind('_') {
        let suffix = &stripped[last_underscore + 1..];
        // Check if suffix is purely numeric (drive strength)
        if !suffix.is_empty() && suffix.chars().all(|c| c.is_ascii_digit()) {
            return &stripped[..last_underscore];
        }
    }

    stripped
}

/// Return Direction::I as fallback but log an error.
fn unknown_pin(macro_name: &CompactString, pin_name: &CompactString) -> Direction {
    panic!("Unknown SKY130 pin: macro={}, pin={}", macro_name, pin_name);
}

/// Check if a cell name is a SKY130 standard cell or associated macro.
pub fn is_sky130_cell(name: &str) -> bool {
    name.starts_with("sky130_fd_sc_") || name.starts_with("CF_SRAM_")
}

/// Check if a cell name is an AIGPDK cell.
pub fn is_aigpdk_cell(name: &str) -> bool {
    matches!(
        name,
        "INV"
            | "BUF"
            | "CKLNQD"
            | "AND2_00_0"
            | "AND2_01_0"
            | "AND2_10_0"
            | "AND2_11_0"
            | "AND2_11_1"
            | "DFF"
            | "DFFSR"
            | "LATCH"
            | "GEM_ASSERT"
            | "GEM_DISPLAY"
    ) || name.starts_with("$__RAMGEM_")
}

// `CellLibrary`, `detect_library`, `detect_library_from_file` (and the
// private `resolve_library` helper) now live in `crate::pdk`. They were
// PDK-shared from the start; their old location in this SKY130 module
// was a Phase 4 deferred-cleanup item.

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_extract_cell_type() {
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__inv_2"), "inv");
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__nand2_4"), "nand2");
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__dfxtp_1"), "dfxtp");
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__a21oi_1"), "a21oi");
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__o21ai_0"), "o21ai");
        assert_eq!(extract_cell_type("sky130_fd_sc_hs__buf_16"), "buf");
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__edfxtp_1"), "edfxtp");
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__fa_1"), "fa");
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__ha_1"), "ha");
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__mux2i_1"), "mux2i");
        assert_eq!(extract_cell_type("sky130_fd_sc_hd__conb_1"), "conb");
    }

    #[test]
    fn test_is_sky130_cell() {
        assert!(is_sky130_cell("sky130_fd_sc_hd__inv_2"));
        assert!(is_sky130_cell("sky130_fd_sc_hs__nand2_4"));
        assert!(!is_sky130_cell("AND2_00_0"));
        assert!(!is_sky130_cell("INV"));
    }

    #[test]
    fn test_pin_directions() {
        let provider = SKY130LeafPins;

        // Test inverter
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__inv_2".into(), &"A".into(), None),
            Direction::I
        );
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__inv_2".into(), &"Y".into(), None),
            Direction::O
        );

        // Test buffer
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__buf_4".into(), &"A".into(), None),
            Direction::I
        );
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__buf_4".into(), &"X".into(), None),
            Direction::O
        );

        // Test NAND2
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__nand2_1".into(), &"A".into(), None),
            Direction::I
        );
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__nand2_1".into(), &"B".into(), None),
            Direction::I
        );
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__nand2_1".into(), &"Y".into(), None),
            Direction::O
        );

        // Test DFF
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__dfxtp_1".into(), &"CLK".into(), None),
            Direction::I
        );
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__dfxtp_1".into(), &"D".into(), None),
            Direction::I
        );
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__dfxtp_1".into(), &"Q".into(), None),
            Direction::O
        );

        // Test conb
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__conb_1".into(), &"HI".into(), None),
            Direction::O
        );
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__conb_1".into(), &"LO".into(), None),
            Direction::O
        );
    }

    #[test]
    fn test_is_aigpdk_cell() {
        assert!(is_aigpdk_cell("AND2_00_0"));
        assert!(is_aigpdk_cell("INV"));
        assert!(is_aigpdk_cell("BUF"));
        assert!(is_aigpdk_cell("DFF"));
        assert!(is_aigpdk_cell("DFFSR"));
        assert!(is_aigpdk_cell("$__RAMGEM_SYNC_"));
        assert!(!is_aigpdk_cell("sky130_fd_sc_hd__inv_2"));
    }

    // `test_detect_library` was moved alongside `detect_library` itself,
    // into `crate::pdk::tests`.

    /// Regression gate for the shadow bug that previously hid the
    /// `bufinv_*` family behind a `t.starts_with("buf")` arm in the
    /// hand-rolled `direction_of`. With exact lookup, `bufinv::Y` must
    /// resolve to `Direction::O` and `bufinv::A` to `Direction::I`.
    #[test]
    fn bufinv_resolves_after_table_switch() {
        let provider = SKY130LeafPins;
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__bufinv_1".into(), &"A".into(), None,),
            Direction::I,
        );
        assert_eq!(
            provider.direction_of(&"sky130_fd_sc_hd__bufinv_1".into(), &"Y".into(), None,),
            Direction::O,
        );
    }
}
